### PR TITLE
Update 0.6

### PR DESCRIPTION
**Pull request by Edocsyl**
Hi

What i did:
- Channel Search
- UI Improvements
  - Page Scroll
  - Game / Stream selector 
  - Menu redesign
  - bug fixes

Watch the README there is a photo.

Could you update the Download Zip?

Thanks & Regards
Kaj

### CODE REVIEW

**Comment by PatrickRorth** [comment]
Just FYI - LG updates there Developer ToS

"access to the USB App Test service for webOS TV is now strictly limited to the webOS TV partners with NDA ONLY. "

I can no longer upload the project, and get the files out. I will try find an other solution.

**Comment by Edocsyl** [comment]
I cloud make a seller account at lg. Maybe we can load the app up to the lg app store.

**Comment by PatrickRorth** [comment]
If you're up for it, go for it. Would be great!

**Comment by PatrickRorth** [comment]
Hi mate

How is it going with the account creation for the LG store ? :)

**Comment by Edocsyl** [comment]
Hi

I've created one. But we need to develop a stable 1.0 version. You can't upload a lower version than 1.0. But for a 1.0 version we need to develop the usability with the tv remote. I think this is one of the key features that we need to focus on.

**Comment by PatrickRorth** [comment]
Sounds great!

I agree! I tried looking into it earlier in webos 1, but im not sure if things have changed.

**Comment by Edocsyl** [comment]
I think nothing changed on the html5 side with webos 3. i found this example https://developer.lge.com/webOSTV/develop/web-app/code-samples-html/remote-control/ its like you use the keyboard on your computer.

**Pull request merged**
